In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [2]:
df= pd.read_excel('laptopdata/lapexcel.xlsx')

In [3]:
df.shape

(49, 7)

In [4]:
df.columns

Index(['Product', 'Processor', 'Ram', 'Memory', 'OS ', 'Size', 'Price'], dtype='object')

In [5]:
df.describe()

,Product,Processor,Ram,Memory,OS,Size,Price
count,49,49,49,49,49,49,49
unique,47,24,9,4,2,8,46
top,Asus UX581LV-H2035T,12th Gen Intel Core i7 12700H,32 GB DDR5 RAM,1 TB SSD,Windows 11 OS,15.6 inches,"1,61,990"
freq,2,9,21,22,45,14,2

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Product    49 non-null     object
 1   Processor  49 non-null     object
 2   Ram        49 non-null     object
 3   Memory     49 non-null     object
 4   OS         49 non-null     object
 5   Size       49 non-null     object
 6   Price      49 non-null     object
dtypes: object(7)
memory usage: 2.8+ KB

In [7]:
df.isnull().sum()

Product      0
Processor    0
Ram          0
Memory       0
OS           0
Size         0
Price        0
dtype: int64

In [8]:
def unique_print(df):
    for column in df.columns:
        print(f'Unique values in column {column} are : {df[column].unique()}\n')

In [9]:
unique_print(df)

Unique values in column Product are : ['MSI Stealth GS77 12UHS-226IN' 'MSI Titan GT77 HX 13VI-092IN'
 'Acer Predator Helios 500 Ph517-52' 'MSI Titan GT77 HX 13VH-093IN'
 'MSI Stealth GS66 12UGS-290IN' 'MSI GT77 Titan 12UHS-054IN'
 'Asus ROG Zephyrus Duo 16' 'MSI Gaming Raider GE66 12UHS-218IN'
 'Asus ROG Zephyrus Duo 16 (2023)' 'MSI Creator Z16P B12UMST-211IN'
 'Dell XPS 9720' 'Asus ROG Zephyrus Duo 16 2022'
 'Dell Alienware X17 R2 D569943WIN9' 'Lenovo Legion 5 Pro 82RF00E1IN'
 'HP Omen 17-ck1023TX' 'Asus ROG Zephyrus Duo 16 2022 GX650RXZ-LO227WS'
 'Asus ROG Zephyrus Duo 16 2022 GX650RXZ-LS228WS'
 'Asus ZenBook Pro Duo 15 OLED 2022 UX582ZM-H701WS'
 'Asus ROG Flow X13 GV301QH-K5459TS' 'Asus UX581LV-H2035T'
 'Asus ROG Zephyrus G14 2023 GA402XV-N2034WS'
 'Asus ROG Zephyrus G14 2023 GA402XZ-N2020WS'
 'Asus ROG Strix SCAR 16 2023 G634JY-NM054WS'
 'Asus Vivobook Pro 16X OLED N7601ZM-MQ931WS'
 'MSI Creator Z16P B12UKST-210IN' 'Asus ROG Strix Scar 15 G533ZXZ-LN116WS'
 'Asus ROG Zephyrus G14 2022 GA402RK-L8148WS'
 'Acer Predator Triton 500 SE PT516-52s NH.QFQSI.001'
 'Asus ROG Zephyrus S15 GX502LXS-HF081T'
 'Asus ROG Strix G17 2023 G713PU-LL060WS'
 'Asus ROG Zephyrus G16 2023 GU603VV-N4044WS'
 'Asus ROG Strix Scar 17 2023 G733PZ-LL046WS'
 'MSI Raider GE77HX 12UHS-205IN' 'Razer Blade 15 Advanced Gaming Laptop'
 'HP Victus 16-d0333TX' 'Asus Vivobook 16X 2022 M1603QA-MB502WS'
 'Asus Vivobook 16X 2023 K3605VC-MB951WS' 'HP Victus 15-fb0106AX'
 'Asus TUF Gaming A15 FA506IHRZ-HN111W\xa0' 'HP Victus 15-fb0121AX'
 'Lenovo IdeaPad Gaming 3 15IHU6 82K101B6IN'
 'Asus TUF Gaming A15 2022 FA577RE-HN055WS'
 'Asus ROG Flow Z13-ACRNM RMT02 GZ301VIC-MU004WS' 'Lenovo V15 G3 IAP'
 'HP Victus 16-d0302TX' 'HP Victus 15-fa1066TX'
 'Lenovo Legion 5 82RB00K8IN']

Unique values in column Processor are : ['12th Gen Core i9' '13th Gen Intel Core i9 13980HX'
 '11th Gen Intel Core i9 11980HK' '12th Gen Intel Core i7 12700H'
 '12th Gen Intel Core i9 12900HX' '7th Gen AMD Ryzen 9 7945HX'
 '12th Gen Intel Core i9 12900H' '6th Gen AMD Ryzen 9 6900HX'
 '5th Gen AMD Ryzen 9 5980HS' '10th Gen Intel Core i9 10980HK'
 '7th Gen AMD Ryzen 9 7940HS' '12th Gen Intel Core i9 12900HK'
 '6th Gen AMD Ryzen 9 6900HS\u200b' '10th Gen Intel Core i7 10875H'
 '7th Gen AMD Ryzen 9 7845HX' '13th Gen Intel Core i9 13900H'
 '10th Gen Intel Core i7-10875H' '11th Gen Intel Core i5 11400H'
 '5th Gen AMD Ryzen 5 5600H' '4th Gen AMD Ryzen 5 4600H'
 '11th Gen Intel Core i5 11320H' '6th Gen AMD Ryzen 7 6800H'
 '12th Gen Intel Core i3 1215U' '13th Gen Intel Core i7 13700H']

Unique values in column Ram are : ['32\u2009GB DDR5 RAM' '64\u2009GB DDR5 RAM' '64\u2009GB DDR4 RAM'
 '16\u2009GB DDR5 RAM' '32\u2009GB LPDDR5 RAM' '32\u2009GB DDR4 RAM'
 '32\u2009GB LPDDR4X RAM' '16\u2009GB DDR4 RAM' '8\u2009GB DDR4 RAM']

Unique values in column Memory are : ['2\u2009TB SSD' '4\u2009TB SSD' '1\u2009TB SSD' '512\u2009GB SSD']

Unique values in column OS  are : ['Windows 11 OS' 'Windows 10 OS']

Unique values in column Size are : ['17.3\u2009inches' '15.6\u2009inches' '16\u2009inches' '17\u2009inches'
 '13.4\u2009inches' '14\u2009inches' '15.6 inches' '16.1\u2009inches']

Unique values in column Price are : ['3,00,990' '5,99,990' '4,42,605' '4,89,990' '1,95,990' '4,99,990'
 '4,29,990' '4,10,990' '3,79,990' '4,85,990' '2,72,490' '3,98,589'
 '3,00,490' '2,17,001' '2,96,000' '3,91,990' '3,61,990' '1,99,990'
 '1,99,991' '1,61,990' '2,66,990' '3,39,990' '1,85,000' '3,81,216'
 '3,35,990' '2,74,990' '1,76,990' '2,24,990' '2,34,990' '1,59,990'
 '1,79,990' '2,69,990' '2,99,990' '4,16,442' 58990 49490 '1,09,990' 64990
 49990 54990 81990 '2,84,990' 39999 64899 '1,12,990' '1,19,990']

In [10]:
print(df.groupby('Processor')['Processor'].agg('count').max())
print(df.groupby('Processor')['Processor'].agg('count').min())

9
1

In [11]:
df.head()

,Product,Processor,Ram,Memory,OS,Size,Price
0,MSI Stealth GS77 12UHS-226IN,12th Gen Core i9,32 GB DDR5 RAM,2 TB SSD,Windows 11 OS,17.3 inches,"3,00,990"
1,MSI Titan GT77 HX 13VI-092IN,13th Gen Intel Core i9 13980HX,64 GB DDR5 RAM,4 TB SSD,Windows 11 OS,17.3 inches,"5,99,990"
2,Acer Predator Helios 500 Ph517-52,11th Gen Intel Core i9 11980HK,64 GB DDR4 RAM,2 TB SSD,Windows 10 OS,17.3 inches,"4,42,605"
3,MSI Titan GT77 HX 13VH-093IN,13th Gen Intel Core i9 13980HX,64 GB DDR5 RAM,2 TB SSD,Windows 11 OS,17.3 inches,"4,89,990"
4,MSI Stealth GS66 12UGS-290IN,12th Gen Intel Core i7 12700H,32 GB DDR5 RAM,1 TB SSD,Windows 11 OS,15.6 inches,"1,95,990"

In [12]:
df=df.dropna()
#just in case

In [13]:
def get_name(x):
    temp=x.split(' ')
    return temp[0]

In [14]:
df['company']=df['Product'].apply(lambda x: get_name(x))

In [15]:
df.head()

,Product,Processor,Ram,Memory,OS,Size,Price,company
0,MSI Stealth GS77 12UHS-226IN,12th Gen Core i9,32 GB DDR5 RAM,2 TB SSD,Windows 11 OS,17.3 inches,"3,00,990",MSI
1,MSI Titan GT77 HX 13VI-092IN,13th Gen Intel Core i9 13980HX,64 GB DDR5 RAM,4 TB SSD,Windows 11 OS,17.3 inches,"5,99,990",MSI
2,Acer Predator Helios 500 Ph517-52,11th Gen Intel Core i9 11980HK,64 GB DDR4 RAM,2 TB SSD,Windows 10 OS,17.3 inches,"4,42,605",Acer
3,MSI Titan GT77 HX 13VH-093IN,13th Gen Intel Core i9 13980HX,64 GB DDR5 RAM,2 TB SSD,Windows 11 OS,17.3 inches,"4,89,990",MSI
4,MSI Stealth GS66 12UGS-290IN,12th Gen Intel Core i7 12700H,32 GB DDR5 RAM,1 TB SSD,Windows 11 OS,15.6 inches,"1,95,990",MSI

In [16]:
df.Product.unique()

array(['MSI Stealth GS77 12UHS-226IN', 'MSI Titan GT77 HX 13VI-092IN',
       'Acer Predator Helios 500 Ph517-52',
       'MSI Titan GT77 HX 13VH-093IN', 'MSI Stealth GS66 12UGS-290IN',
       'MSI GT77 Titan 12UHS-054IN', 'Asus ROG Zephyrus Duo 16',
       'MSI Gaming Raider GE66 12UHS-218IN',
       'Asus ROG Zephyrus Duo 16 (2023)',
       'MSI Creator Z16P B12UMST-211IN', 'Dell XPS 9720',
       'Asus ROG Zephyrus Duo 16 2022',
       'Dell Alienware X17 R2 D569943WIN9',
       'Lenovo Legion 5 Pro 82RF00E1IN', 'HP Omen 17-ck1023TX',
       'Asus ROG Zephyrus Duo 16 2022 GX650RXZ-LO227WS',
       'Asus ROG Zephyrus Duo 16 2022 GX650RXZ-LS228WS',
       'Asus ZenBook Pro Duo 15 OLED 2022 UX582ZM-H701WS',
       'Asus ROG Flow X13 GV301QH-K5459TS', 'Asus UX581LV-H2035T',
       'Asus ROG Zephyrus G14 2023 GA402XV-N2034WS',
       'Asus ROG Zephyrus G14 2023 GA402XZ-N2020WS',
       'Asus ROG Strix SCAR 16 2023 G634JY-NM054WS',
       'Asus Vivobook Pro 16X OLED N7601ZM-MQ931WS',
       'MSI Creator Z16P B12UKST-210IN',
       'Asus ROG Strix Scar 15 G533ZXZ-LN116WS',
       'Asus ROG Zephyrus G14 2022 GA402RK-L8148WS',
       'Acer Predator Triton 500 SE PT516-52s NH.QFQSI.001',
       'Asus ROG Zephyrus S15 GX502LXS-HF081T',
       'Asus ROG Strix G17 2023 G713PU-LL060WS',
       'Asus ROG Zephyrus G16 2023 GU603VV-N4044WS',
       'Asus ROG Strix Scar 17 2023 G733PZ-LL046WS',
       'MSI Raider GE77HX 12UHS-205IN',
       'Razer Blade 15 Advanced Gaming Laptop', 'HP Victus 16-d0333TX',
       'Asus Vivobook 16X 2022 M1603QA-MB502WS',
       'Asus Vivobook 16X 2023 K3605VC-MB951WS', 'HP Victus 15-fb0106AX',
       'Asus TUF Gaming A15 FA506IHRZ-HN111W\xa0',
       'HP Victus 15-fb0121AX',
       'Lenovo IdeaPad Gaming 3 15IHU6 82K101B6IN',
       'Asus TUF Gaming A15 2022 FA577RE-HN055WS',
       'Asus ROG Flow Z13-ACRNM RMT02 GZ301VIC-MU004WS',
       'Lenovo V15 G3 IAP', 'HP Victus 16-d0302TX',
       'HP Victus 15-fa1066TX', 'Lenovo Legion 5 82RB00K8IN'],
      dtype=object)

In [17]:
df.Processor.unique()

array(['12th Gen Core i9', '13th Gen Intel Core i9 13980HX',
       '11th Gen Intel Core i9 11980HK', '12th Gen Intel Core i7 12700H',
       '12th Gen Intel Core i9 12900HX', '7th Gen AMD Ryzen 9 7945HX',
       '12th Gen Intel Core i9 12900H', '6th Gen AMD Ryzen 9 6900HX',
       '5th Gen AMD Ryzen 9 5980HS', '10th Gen Intel Core i9 10980HK',
       '7th Gen AMD Ryzen 9 7940HS', '12th Gen Intel Core i9 12900HK',
       '6th Gen AMD Ryzen 9 6900HS\u200b',
       '10th Gen Intel Core i7 10875H', '7th Gen AMD Ryzen 9 7845HX',
       '13th Gen Intel Core i9 13900H', '10th Gen Intel Core i7-10875H',
       '11th Gen Intel Core i5 11400H', '5th Gen AMD Ryzen 5 5600H',
       '4th Gen AMD Ryzen 5 4600H', '11th Gen Intel Core i5 11320H',
       '6th Gen AMD Ryzen 7 6800H', '12th Gen Intel Core i3 1215U',
       '13th Gen Intel Core i7 13700H'], dtype=object)

In [18]:
def get_processor_company(x):
    if 'Intel' in x:
        return 'Intel'
    elif 'AMD' in x:
        return 'AMD' 
def get_processor_gen(x):
    temp=x.split(' ')
    return temp[0]

In [19]:
df['processor_company']= df['Processor'].apply(lambda x: get_processor_company(x))
df['processor_gen']= df['Processor'].apply(lambda x: get_processor_gen(x))

In [20]:
df['processor_company'].fillna(method='bfill', inplace=True)
df['processor_company'].unique()

array(['Intel', 'AMD'], dtype=object)

In [21]:
df.processor_gen.unique()

array(['12th', '13th', '11th', '7th', '6th', '5th', '10th', '4th'],
      dtype=object)

In [22]:
df.head()

,Product,Processor,Ram,Memory,OS,Size,Price,company,processor_company,processor_gen
0,MSI Stealth GS77 12UHS-226IN,12th Gen Core i9,32 GB DDR5 RAM,2 TB SSD,Windows 11 OS,17.3 inches,"3,00,990",MSI,Intel,12th
1,MSI Titan GT77 HX 13VI-092IN,13th Gen Intel Core i9 13980HX,64 GB DDR5 RAM,4 TB SSD,Windows 11 OS,17.3 inches,"5,99,990",MSI,Intel,13th
2,Acer Predator Helios 500 Ph517-52,11th Gen Intel Core i9 11980HK,64 GB DDR4 RAM,2 TB SSD,Windows 10 OS,17.3 inches,"4,42,605",Acer,Intel,11th
3,MSI Titan GT77 HX 13VH-093IN,13th Gen Intel Core i9 13980HX,64 GB DDR5 RAM,2 TB SSD,Windows 11 OS,17.3 inches,"4,89,990",MSI,Intel,13th
4,MSI Stealth GS66 12UGS-290IN,12th Gen Intel Core i7 12700H,32 GB DDR5 RAM,1 TB SSD,Windows 11 OS,15.6 inches,"1,95,990",MSI,Intel,12th

In [23]:
def get_num_mem(x):
    temp=x.split('\u2009')
    return float(temp[0])
def get_num(x):
    temp=x.split(' ')
    return float(temp[0])

In [24]:
df['Memory'].unique()

array(['2\u2009TB SSD', '4\u2009TB SSD', '1\u2009TB SSD',
       '512\u2009GB SSD'], dtype=object)

In [25]:
def func(x):
    if '\u2009' in x:
        return get_num_mem(x)
    elif ' ' in x:
        return get_num(x)
def get_core(x):
    possible_cores=['i9','i7','i5','i3','9','5','7','3']
    temp=x.split(' ')
    for core in possible_cores:
        if core in temp:
            return core
    return None

def get_gen(x):
    possible_gen=[str(i)+"th" for i in range(15) if i!=0]
    temp=x.split(' ')
    for gen in possible_gen:
        if gen in temp:
            temp2=gen.split('t')
            gen_num=float(temp2[0]) 
            return gen_num
    return None

In [26]:
df.head()

,Product,Processor,Ram,Memory,OS,Size,Price,company,processor_company,processor_gen
0,MSI Stealth GS77 12UHS-226IN,12th Gen Core i9,32 GB DDR5 RAM,2 TB SSD,Windows 11 OS,17.3 inches,"3,00,990",MSI,Intel,12th
1,MSI Titan GT77 HX 13VI-092IN,13th Gen Intel Core i9 13980HX,64 GB DDR5 RAM,4 TB SSD,Windows 11 OS,17.3 inches,"5,99,990",MSI,Intel,13th
2,Acer Predator Helios 500 Ph517-52,11th Gen Intel Core i9 11980HK,64 GB DDR4 RAM,2 TB SSD,Windows 10 OS,17.3 inches,"4,42,605",Acer,Intel,11th
3,MSI Titan GT77 HX 13VH-093IN,13th Gen Intel Core i9 13980HX,64 GB DDR5 RAM,2 TB SSD,Windows 11 OS,17.3 inches,"4,89,990",MSI,Intel,13th
4,MSI Stealth GS66 12UGS-290IN,12th Gen Intel Core i7 12700H,32 GB DDR5 RAM,1 TB SSD,Windows 11 OS,15.6 inches,"1,95,990",MSI,Intel,12th

In [27]:
df.Processor.unique()

array(['12th Gen Core i9', '13th Gen Intel Core i9 13980HX',
       '11th Gen Intel Core i9 11980HK', '12th Gen Intel Core i7 12700H',
       '12th Gen Intel Core i9 12900HX', '7th Gen AMD Ryzen 9 7945HX',
       '12th Gen Intel Core i9 12900H', '6th Gen AMD Ryzen 9 6900HX',
       '5th Gen AMD Ryzen 9 5980HS', '10th Gen Intel Core i9 10980HK',
       '7th Gen AMD Ryzen 9 7940HS', '12th Gen Intel Core i9 12900HK',
       '6th Gen AMD Ryzen 9 6900HS\u200b',
       '10th Gen Intel Core i7 10875H', '7th Gen AMD Ryzen 9 7845HX',
       '13th Gen Intel Core i9 13900H', '10th Gen Intel Core i7-10875H',
       '11th Gen Intel Core i5 11400H', '5th Gen AMD Ryzen 5 5600H',
       '4th Gen AMD Ryzen 5 4600H', '11th Gen Intel Core i5 11320H',
       '6th Gen AMD Ryzen 7 6800H', '12th Gen Intel Core i3 1215U',
       '13th Gen Intel Core i7 13700H'], dtype=object)

In [28]:
temp=df['Processor'][0].split(' ')
temp[0][:2]

'12'

In [29]:
df['processor_gen']=df['Processor'].apply(lambda x: get_gen(x))
df.head()

,Product,Processor,Ram,Memory,OS,Size,Price,company,processor_company,processor_gen
0,MSI Stealth GS77 12UHS-226IN,12th Gen Core i9,32 GB DDR5 RAM,2 TB SSD,Windows 11 OS,17.3 inches,"3,00,990",MSI,Intel,12.0
1,MSI Titan GT77 HX 13VI-092IN,13th Gen Intel Core i9 13980HX,64 GB DDR5 RAM,4 TB SSD,Windows 11 OS,17.3 inches,"5,99,990",MSI,Intel,13.0
2,Acer Predator Helios 500 Ph517-52,11th Gen Intel Core i9 11980HK,64 GB DDR4 RAM,2 TB SSD,Windows 10 OS,17.3 inches,"4,42,605",Acer,Intel,11.0
3,MSI Titan GT77 HX 13VH-093IN,13th Gen Intel Core i9 13980HX,64 GB DDR5 RAM,2 TB SSD,Windows 11 OS,17.3 inches,"4,89,990",MSI,Intel,13.0
4,MSI Stealth GS66 12UGS-290IN,12th Gen Intel Core i7 12700H,32 GB DDR5 RAM,1 TB SSD,Windows 11 OS,15.6 inches,"1,95,990",MSI,Intel,12.0

In [30]:
df['processor_cores']=df['Processor'].apply(lambda x: get_core(x))
df.head()

,Product,Processor,Ram,Memory,OS,Size,Price,company,processor_company,processor_gen,processor_cores
0,MSI Stealth GS77 12UHS-226IN,12th Gen Core i9,32 GB DDR5 RAM,2 TB SSD,Windows 11 OS,17.3 inches,"3,00,990",MSI,Intel,12.0,i9
1,MSI Titan GT77 HX 13VI-092IN,13th Gen Intel Core i9 13980HX,64 GB DDR5 RAM,4 TB SSD,Windows 11 OS,17.3 inches,"5,99,990",MSI,Intel,13.0,i9
2,Acer Predator Helios 500 Ph517-52,11th Gen Intel Core i9 11980HK,64 GB DDR4 RAM,2 TB SSD,Windows 10 OS,17.3 inches,"4,42,605",Acer,Intel,11.0,i9
3,MSI Titan GT77 HX 13VH-093IN,13th Gen Intel Core i9 13980HX,64 GB DDR5 RAM,2 TB SSD,Windows 11 OS,17.3 inches,"4,89,990",MSI,Intel,13.0,i9
4,MSI Stealth GS66 12UGS-290IN,12th Gen Intel Core i7 12700H,32 GB DDR5 RAM,1 TB SSD,Windows 11 OS,15.6 inches,"1,95,990",MSI,Intel,12.0,i7

In [31]:
df.dropna(subset=['processor_cores'],inplace=True)

In [32]:
df.processor_cores.unique()

array(['i9', 'i7', '9', 'i5', '5', '7', 'i3'], dtype=object)

In [33]:
#dropped a row where processor_core was not mentioned
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 48 entries, 0 to 48
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Product            48 non-null     object
 1   Processor          48 non-null     object
 2   Ram                48 non-null     object
 3   Memory             48 non-null     object
 4   OS                 48 non-null     object
 5   Size               48 non-null     object
 6   Price              48 non-null     object
 7   company            48 non-null     object
 8   processor_company  48 non-null     object
 9   processor_gen      48 non-null     float64
 10  processor_cores    48 non-null     object
dtypes: float64(1), object(10)
memory usage: 4.5+ KB

In [34]:
df['Ram_in_GB']=df['Ram'].apply(lambda x: get_num_mem(x))
df['size_in_inches']=df['Size'].apply(lambda x: func(x))
df['Memory']=df['Memory'].apply(lambda x: func(x))

In [35]:
df.size_in_inches.dtype

dtype('float64')

In [36]:
df['Memory'].unique()

array([  2.,   4.,   1., 512.])

In [37]:
def get_os(x):
    temp=x.split(' ')
    return float(temp[1])

In [38]:
df2=df.copy()

In [39]:
df2.rename(columns={'OS ': 'OS'},inplace=True)
#os had a space so removing it
df2['OS']= df2['OS'].apply(lambda x: get_os(x))

In [40]:
df2.columns

Index(['Product', 'Processor', 'Ram', 'Memory', 'OS', 'Size', 'Price',
       'company', 'processor_company', 'processor_gen', 'processor_cores',
       'Ram_in_GB', 'size_in_inches'],
      dtype='object')

In [41]:
df2.head()

,Product,Processor,Ram,Memory,OS,Size,Price,company,processor_company,processor_gen,processor_cores,Ram_in_GB,size_in_inches
0,MSI Stealth GS77 12UHS-226IN,12th Gen Core i9,32 GB DDR5 RAM,2.0,11.0,17.3 inches,"3,00,990",MSI,Intel,12.0,i9,32.0,17.3
1,MSI Titan GT77 HX 13VI-092IN,13th Gen Intel Core i9 13980HX,64 GB DDR5 RAM,4.0,11.0,17.3 inches,"5,99,990",MSI,Intel,13.0,i9,64.0,17.3
2,Acer Predator Helios 500 Ph517-52,11th Gen Intel Core i9 11980HK,64 GB DDR4 RAM,2.0,10.0,17.3 inches,"4,42,605",Acer,Intel,11.0,i9,64.0,17.3
3,MSI Titan GT77 HX 13VH-093IN,13th Gen Intel Core i9 13980HX,64 GB DDR5 RAM,2.0,11.0,17.3 inches,"4,89,990",MSI,Intel,13.0,i9,64.0,17.3
4,MSI Stealth GS66 12UGS-290IN,12th Gen Intel Core i7 12700H,32 GB DDR5 RAM,1.0,11.0,15.6 inches,"1,95,990",MSI,Intel,12.0,i7,32.0,15.6

In [42]:
df2.drop(['Ram','Size'],axis=1,inplace=True)

In [43]:
df2.dtypes

Product               object
Processor             object
Memory               float64
OS                   float64
Price                 object
company               object
processor_company     object
processor_gen        float64
processor_cores       object
Ram_in_GB            float64
size_in_inches       float64
dtype: object

In [44]:
#in prices some are numbers some are integers
def is_float(x):
    try:
        float(x)
    except:
        return False
    return True

In [45]:
def get_price(x):
    if not is_float(x):
        temp=x.split(',')
        price=''
        for part in temp:
            price+=part
        return float(price)
    else :
        return float(x)

In [46]:
df2['Price']=df2['Price'].apply(lambda x: get_price(x))

In [47]:
df2.Price.info

<bound method Series.info of 0     300990.0
1     599990.0
2     442605.0
3     489990.0
4     195990.0
5     499990.0
6     429990.0
7     410990.0
8     379990.0
9     485990.0
10    272490.0
11    398589.0
12    300490.0
13    217001.0
14    296000.0
15    391990.0
16    361990.0
17    199990.0
18    199991.0
19    161990.0
20    161990.0
21    199990.0
22    266990.0
23    339990.0
24    185000.0
25    381216.0
26    335990.0
27    274990.0
28    176990.0
29    224990.0
30    234990.0
31    159990.0
32    179990.0
33    269990.0
34    299990.0
36     58990.0
37     49490.0
38    109990.0
39     64990.0
40     49990.0
41     54990.0
42     49990.0
43     81990.0
44    284990.0
45     39999.0
46     64899.0
47    112990.0
48    119990.0
Name: Price, dtype: float64>

In [48]:
df2.dtypes

Product               object
Processor             object
Memory               float64
OS                   float64
Price                float64
company               object
processor_company     object
processor_gen        float64
processor_cores       object
Ram_in_GB            float64
size_in_inches       float64
dtype: object

In [49]:
df.groupby('processor_company')['processor_company'].agg('count')
df.groupby('processor_gen')['processor_gen'].agg('count')

processor_gen
4.0      1
5.0      4
6.0      5
7.0      6
10.0     3
11.0     4
12.0    18
13.0     7
Name: processor_gen, dtype: int64

In [50]:
df2.Processor.unique().shape
df2.drop(['Product','Processor'],axis=1,inplace=True)
one_hot_columns=['processor_company','processor_gen','company','processor_cores','Memory']

In [51]:
df2.head()

,Memory,OS,Price,company,processor_company,processor_gen,processor_cores,Ram_in_GB,size_in_inches
0,2.0,11.0,300990.0,MSI,Intel,12.0,i9,32.0,17.3
1,4.0,11.0,599990.0,MSI,Intel,13.0,i9,64.0,17.3
2,2.0,10.0,442605.0,Acer,Intel,11.0,i9,64.0,17.3
3,2.0,11.0,489990.0,MSI,Intel,13.0,i9,64.0,17.3
4,1.0,11.0,195990.0,MSI,Intel,12.0,i7,32.0,15.6

In [52]:
df3=pd.get_dummies(df2[one_hot_columns])
df4=df2.drop(one_hot_columns,axis=1)

In [53]:
df_final= pd.concat([df4,df3],axis='columns')

In [54]:
df_final.head()

,OS,Price,Ram_in_GB,size_in_inches,processor_gen,Memory,processor_company_AMD,processor_company_Intel,company_Acer,company_Asus,...,company_HP,company_Lenovo,company_MSI,processor_cores_5,processor_cores_7,processor_cores_9,processor_cores_i3,processor_cores_i5,processor_cores_i7,processor_cores_i9
0,11.0,300990.0,32.0,17.3,12.0,2.0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,1
1,11.0,599990.0,64.0,17.3,13.0,4.0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,1
2,10.0,442605.0,64.0,17.3,11.0,2.0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,1
3,11.0,489990.0,64.0,17.3,13.0,2.0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,1
4,11.0,195990.0,32.0,15.6,12.0,1.0,0,1,0,0,...,0,0,1,0,0,0,0,0,1,0

In [55]:
df_final['processor_company_AMD']

0     0
1     0
2     0
3     0
4     0
5     0
6     1
7     0
8     1
9     0
10    0
11    1
12    0
13    0
14    0
15    1
16    1
17    0
18    1
19    0
20    0
21    1
22    1
23    0
24    0
25    0
26    0
27    0
28    1
29    0
30    0
31    1
32    0
33    1
34    0
36    0
37    1
38    0
39    1
40    1
41    1
42    0
43    1
44    0
45    0
46    0
47    0
48    0
Name: processor_company_AMD, dtype: uint8

In [56]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 48 entries, 0 to 48
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   OS                       48 non-null     float64
 1   Price                    48 non-null     float64
 2   Ram_in_GB                48 non-null     float64
 3   size_in_inches           48 non-null     float64
 4   processor_gen            48 non-null     float64
 5   Memory                   48 non-null     float64
 6   processor_company_AMD    48 non-null     uint8
 7   processor_company_Intel  48 non-null     uint8
 8   company_Acer             48 non-null     uint8
 9   company_Asus             48 non-null     uint8
 10  company_Dell             48 non-null     uint8
 11  company_HP               48 non-null     uint8
 12  company_Lenovo           48 non-null     uint8
 13  company_MSI              48 non-null     uint8
 14  processor_cores_5        48 non-null     uint8
 15  processor_cores_7        48 non-null     uint8
 16  processor_cores_9        48 non-null     uint8
 17  processor_cores_i3       48 non-null     uint8
 18  processor_cores_i5       48 non-null     uint8
 19  processor_cores_i7       48 non-null     uint8
 20  processor_cores_i9       48 non-null     uint8
dtypes: float64(6), uint8(15)
memory usage: 3.3 KB

In [57]:
df_final.head()

,OS,Price,Ram_in_GB,size_in_inches,processor_gen,Memory,processor_company_AMD,processor_company_Intel,company_Acer,company_Asus,...,company_HP,company_Lenovo,company_MSI,processor_cores_5,processor_cores_7,processor_cores_9,processor_cores_i3,processor_cores_i5,processor_cores_i7,processor_cores_i9
0,11.0,300990.0,32.0,17.3,12.0,2.0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,1
1,11.0,599990.0,64.0,17.3,13.0,4.0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,1
2,10.0,442605.0,64.0,17.3,11.0,2.0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,1
3,11.0,489990.0,64.0,17.3,13.0,2.0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,1
4,11.0,195990.0,32.0,15.6,12.0,1.0,0,1,0,0,...,0,0,1,0,0,0,0,0,1,0

In [58]:
from sklearn.preprocessing import StandardScaler

scaler= StandardScaler()

X= df_final.drop('Price',axis=1)
y=df_final['Price']
cols_to_scale=['size_in_inches','Ram_in_GB','processor_gen']

y_scaler=StandardScaler()

X[cols_to_scale]=scaler.fit_transform(X[cols_to_scale])
#y['Price']=y_scaler.fit_transform(y['Price'])

In [59]:
X.head()

,OS,Ram_in_GB,size_in_inches,processor_gen,Memory,processor_company_AMD,processor_company_Intel,company_Acer,company_Asus,company_Dell,company_HP,company_Lenovo,company_MSI,processor_cores_5,processor_cores_7,processor_cores_9,processor_cores_i3,processor_cores_i5,processor_cores_i7,processor_cores_i9
0,11.0,0.200895,1.299046,0.706728,2.0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1
1,11.0,2.343773,1.299046,1.049384,4.0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1
2,10.0,2.343773,1.299046,0.364072,2.0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1
3,11.0,2.343773,1.299046,1.049384,2.0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1
4,11.0,0.200895,-0.394279,0.706728,1.0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0

In [60]:
y.head()

0    300990.0
1    599990.0
2    442605.0
3    489990.0
4    195990.0
Name: Price, dtype: float64

In [61]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression




X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=10)

In [62]:
lr_model=LinearRegression()
lr_model.fit(X_train,y_train)
lr_model.score(X_test,y_test)

0.8078950105199718

In [63]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score

cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
cross_val_score(LinearRegression(),X,y,cv=5)

array([ 5.21240252e-01, -3.94779773e-01,  3.67173205e-02, -4.84131474e-01,
       -6.25293578e+04])

In [64]:
from sklearn.linear_model import Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import GridSearchCV

In [65]:
model=LinearRegression()
params=model.get_params()
print(params)

{'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'positive': False}

In [66]:
algo = {
    'linear_regressor':{
        'model':LinearRegression(),
        'params':
        {
            'fit_intercept': [True,False],
            'positive':[True,False]

        }
    },
    'lasso':
    {
        'model':Lasso(),
        'params':{
            'alpha':[1,2],
            'selection':['random','cyclic']
        }
    },
    'decision_tree':{
        'model':DecisionTreeRegressor(),
        'params':{
            'criterion':['squared_error','friedman_mse'],
            'splitter':['best','random']
        }
    }
}

In [67]:
algo.items()

dict_items([('linear_regressor', {'model': LinearRegression(), 'params': {'fit_intercept': [True, False], 'positive': [True, False]}}), ('lasso', {'model': Lasso(), 'params': {'alpha': [1, 2], 'selection': ['random', 'cyclic']}}), ('decision_tree', {'model': DecisionTreeRegressor(), 'params': {'criterion': ['squared_error', 'friedman_mse'], 'splitter': ['best', 'random']}})])

In [68]:
def compute_best_gridsearchcv(X,y):
    scores=[]
    cv=ShuffleSplit(n_splits=5,test_size=0.2,random_state=0)
    for algo_name,config in algo.items():
        gs=GridSearchCV(config['model'],config['params'],cv=cv,return_train_score=False,error_score='raise')  
        gs.fit(X,y)
        scores.append({
            'model':algo_name,
            'best_score':gs.best_score_,
            'best_params':gs.best_params_
        })
    return pd.DataFrame(scores,columns=['model','best_score','best_params'])
compute_best_gridsearchcv(X,y)

d:\Programs\conda\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.315e+10, tolerance: 8.494e+07
  model = cd_fast.enet_coordinate_descent(
d:\Programs\conda\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.917e+10, tolerance: 7.743e+07
  model = cd_fast.enet_coordinate_descent(
d:\Programs\conda\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.565e+10, tolerance: 7.956e+07
  model = cd_fast.enet_coordinate_descent(
d:\Programs\conda\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.557e+10, tolerance: 7.757e+07
  model = cd_fast.enet_coordinate_descent(
d:\Programs\conda\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.964e+10, tolerance: 7.936e+07
  model = cd_fast.enet_coordinate_descent(
d:\Programs\conda\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.188e+10, tolerance: 8.494e+07
  model = cd_fast.enet_coordinate_descent(
d:\Programs\conda\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.129e+10, tolerance: 7.743e+07
  model = cd_fast.enet_coordinate_descent(
d:\Programs\conda\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.331e+10, tolerance: 7.956e+07
  model = cd_fast.enet_coordinate_descent(
d:\Programs\conda\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.646e+09, tolerance: 7.757e+07
  model = cd_fast.enet_coordinate_descent(
d:\Programs\conda\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.024e+09, tolerance: 7.936e+07
  model = cd_fast.enet_coordinate_descent(
d:\Programs\conda\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.383e+10, tolerance: 8.494e+07
  model = cd_fast.enet_coordinate_descent(
d:\Programs\conda\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.739e+10, tolerance: 7.743e+07
  model = cd_fast.enet_coordinate_descent(
d:\Programs\conda\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.506e+10, tolerance: 7.956e+07
  model = cd_fast.enet_coordinate_descent(
d:\Programs\conda\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.242e+10, tolerance: 7.757e+07
  model = cd_fast.enet_coordinate_descent(
d:\Programs\conda\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.987e+10, tolerance: 7.936e+07
  model = cd_fast.enet_coordinate_descent(
d:\Programs\conda\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.191e+10, tolerance: 8.494e+07
  model = cd_fast.enet_coordinate_descent(
d:\Programs\conda\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.355e+10, tolerance: 7.743e+07
  model = cd_fast.enet_coordinate_descent(
d:\Programs\conda\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.975e+08, tolerance: 7.956e+07
  model = cd_fast.enet_coordinate_descent(
d:\Programs\conda\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.657e+09, tolerance: 7.757e+07
  model = cd_fast.enet_coordinate_descent(
d:\Programs\conda\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.035e+09, tolerance: 7.936e+07
  model = cd_fast.enet_coordinate_descent(
d:\Programs\conda\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.486e+10, tolerance: 9.518e+07
  model = cd_fast.enet_coordinate_descent(

,model,best_score,best_params
0,linear_regressor,0.501724,"{'fit_intercept': False, 'positive': True}"
1,lasso,0.451536,"{'alpha': 2, 'selection': 'random'}"
2,decision_tree,0.479992,"{'criterion': 'squared_error', 'splitter': 'be..."

In [69]:
# def predict_price(company,memory,ram,os,size_in_inches):
#     cn_company= 'company_'+str(company)
#     company_index= np.where(X.columns==cn_company)
#     memory_index= np.where(X.columns=='Memory')
#     ram_index=np.where(X.columns=='Ram_in_GB')
#     os_index=np.where(X.columns=='OS')
#     size_in_inches_index=np.where(X.columns=='size_in_inches')
#     x=np.zeros(len(X.columns))
#     x[company_index]=1
#     x[memory_index]=memory
#     x[os_index]=os
#     x[ram_index]=ram
#     x[size_in_inches_index]=size_in_inches
#     cols_to_scale_index=[]
#     for cols in cols_to_scale:
#         if cols in X.columns:
#             cols_to_scale_index.append(np.where(X.columns==cols))
#     x=pd.DataFrame([x])    
#     x[cols_to_scale_index]= scaler.transform(x[cols_to_scale_index])
#     return lr_model.predict([x])

In [70]:
X.columns

Index(['OS', 'Ram_in_GB', 'size_in_inches', 'processor_gen', 'Memory',
       'processor_company_AMD', 'processor_company_Intel', 'company_Acer',
       'company_Asus', 'company_Dell', 'company_HP', 'company_Lenovo',
       'company_MSI', 'processor_cores_5', 'processor_cores_7',
       'processor_cores_9', 'processor_cores_i3', 'processor_cores_i5',
       'processor_cores_i7', 'processor_cores_i9'],
      dtype='object')

In [71]:
X.head()

,OS,Ram_in_GB,size_in_inches,processor_gen,Memory,processor_company_AMD,processor_company_Intel,company_Acer,company_Asus,company_Dell,company_HP,company_Lenovo,company_MSI,processor_cores_5,processor_cores_7,processor_cores_9,processor_cores_i3,processor_cores_i5,processor_cores_i7,processor_cores_i9
0,11.0,0.200895,1.299046,0.706728,2.0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1
1,11.0,2.343773,1.299046,1.049384,4.0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1
2,10.0,2.343773,1.299046,0.364072,2.0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1
3,11.0,2.343773,1.299046,1.049384,2.0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1
4,11.0,0.200895,-0.394279,0.706728,1.0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0

In [72]:
def predict_price(company,processor_company,memory,ram,os,size_in_inches):
    c_col={
        'processor_company_'+str(processor_company):{f'processor_company_{processor_company}':1},
        'company_'+str(company): {f'company_{str(company)}':1},
        'Memory':{'Memory':memory},
        'Ram_in_GB':{'Ram_in_GB':ram},
        'OS':{'OS':os},
        'size_in_inches':{'size_in_inches':size_in_inches}}
    x=pd.DataFrame(columns=X.columns)
    #col_name,col_info=c_col.items()
    c_col_names=[]
    c_col_info=[]
    for name,info in c_col.items():
        c_col_names+=str(name)
        c_col_info+=info
    #print(c_col_names)

    #getting the dataframe with the values given by the user
    for col in X.columns:
        if col in c_col_names:
            # x[col]=c_col[col][col]
            x.loc[0,col]=c_col[col][col]
            #print(x.loc[0,col])
            #print(c_col[col][col])
            #print(x.shape)
        else:
            x.loc[0,col]=0
            pass
        # if col in col_name:
        #     x[col]=col_info[col_name]
        # else:
    #         x[col]=0
    #x.columns=x.columns.str[0]
    print(x.columns)
    x[cols_to_scale]=scaler.transform(x[cols_to_scale])
    #return x
    print(x.shape)

    return lr_model.predict(x)

In [73]:
# y=predict_price('HP','Intel',1,16,11,15)
# print(y.shape)
# print(X.shape)

In [74]:
def feature_mismatch(x,X):
   #assuming column shape is same
   n= x.columns.shape[0]
   flag=0
   for i in range(n):
      if x.columns[i]!=X.columns[i]:
         print(f'x={x.columns[i]} X={X.columns[i]}')
         flag=1
   if flag==1:
      return True
   return False

In [75]:
# b= feature_mismatch(,X)
# print(b)
# print(y.columns)
# print(X.columns)

In [76]:
predict_price('HP','Intel',2,16,11,15)

Index(['OS', 'Ram_in_GB', 'size_in_inches', 'processor_gen', 'Memory',
       'processor_company_AMD', 'processor_company_Intel', 'company_Acer',
       'company_Asus', 'company_Dell', 'company_HP', 'company_Lenovo',
       'company_MSI', 'processor_cores_5', 'processor_cores_7',
       'processor_cores_9', 'processor_cores_i3', 'processor_cores_i5',
       'processor_cores_i7', 'processor_cores_i9'],
      dtype='object')
(1, 20)

array([-1283427.55388196])

In [77]:
import pickle

with open('laptop_price_model.pickle','wb') as f:
    pickle.dump(lr_model,f)

In [78]:
import json
columns={
    'data_columns':[col.lower() for col in X.columns]
}
with open("columns.json","w") as f:
    f.write(json.dumps(columns))

In [79]:
df_final.columns

Index(['OS', 'Price', 'Ram_in_GB', 'size_in_inches', 'processor_gen', 'Memory',
       'processor_company_AMD', 'processor_company_Intel', 'company_Acer',
       'company_Asus', 'company_Dell', 'company_HP', 'company_Lenovo',
       'company_MSI', 'processor_cores_5', 'processor_cores_7',
       'processor_cores_9', 'processor_cores_i3', 'processor_cores_i5',
       'processor_cores_i7', 'processor_cores_i9'],
      dtype='object')

In [80]:
predict_price('MSI','AMD',1,16,11,14)

Index(['OS', 'Ram_in_GB', 'size_in_inches', 'processor_gen', 'Memory',
       'processor_company_AMD', 'processor_company_Intel', 'company_Acer',
       'company_Asus', 'company_Dell', 'company_HP', 'company_Lenovo',
       'company_MSI', 'processor_cores_5', 'processor_cores_7',
       'processor_cores_9', 'processor_cores_i3', 'processor_cores_i5',
       'processor_cores_i7', 'processor_cores_i9'],
      dtype='object')
(1, 20)

array([-1283427.55388196])